spring:
  datasource:
    driver-class-name: 'com.mysql.jdbc.Driver'
    password: Srpp@1973
    username: root
    url: 'jdbc:mysql://localhost:3306/fornecedor'
  jpa:
    hibernate:
      ddl-auto: update
